---
# This playbook deploys a new EC2 instance

- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Create EC2 instance
      ec2:
        key_name: ghuser
        region: us-east-1
        vpc_subnet_id: subnet-b68a16c0
        image: ami-759bc50a # Ubuntu 16.04 hvm:ebs-ssd
        instance_type: t2.nano
        wait: true
        instance_tags:
          Name: "ghuser"

# TODO:
# SG SSH inbound from anywhere
# ssh -i secret.pem ubuntu@54.146.161.0
# ssh -i secret.pem ubuntu@34.233.121.88
# ssh -i secret.pem ubuntu@54.89.167.49 // done, full fetching
# ssh -i secret.pem ubuntu@18.209.45.236 // done
# ssh -i secret.pem ubuntu@34.229.206.109
# ssh -i secret.pem ubuntu@54.174.98.35 // done
# tmux new-session -s 1
# tmux attach -t 1
# curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
# sudo apt-get install -y nodejs
# git clone https://AurelienLourot@github.com/AurelienLourot/ghuser.io.git
